name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - uses: nrwl/nx-set-shas@v3
      - name: Install dependencies
        run: pnpm install
      - run: pnpx nx format:check
      - run: pnpx nx affected -t lint --parallel=3
      - run: pnpx nx affected -t test --parallel=3 --configuration=ci
      - run: pnpx nx affected -t build --parallel=3
